### PR TITLE
Make dummy analyzer less annoying

### PR DESCRIPTION
**Pull request by bzz**
Change it to report only `len(line) > 120` for non-binary files.

### CODE REVIEW

**Comment by bzz** [comment]
will update the tests asap

**Comment by bzz** [comment]
Done.

**Comment by bzz** [comment]
CI on macOS fails with

```
multiple analyzers...no comments from the first analyzer from 'fixtures/double_dummy_config.yml' in '{"analyzer-name":"Dummy2","file":"cmd/lookout/serve.go","line":39,"text":"This line exceeded 120 chars."}
{"analyzer-name":"Dummy2","file":"cmd/lookout/serve.go","line":40,"text":"This line exceeded 120 chars."}
{"analyzer-name":"Dummy2","file":"server.go","line":189,"text":"This line exceeded 120 chars."}
{"analyzer-name":"Dummy2","file":"server_test.go","line":307,"text":"This line exceeded 120 chars."}
{"analyzer-name":"Dummy2","file":"server_test.go","line":316,"text":"This line exceeded 120 chars."}
time="2018-08-27T08:55:00.797362421Z" level=info msg="New status" app=lookout event-id=f9cb6c0fe5007572f6d7310a731ddfb2e243b48e event-type=2 head=refs/heads/master provider= repository="https://github.com/src-d/lookout.git" status=success
```

which seems like a bug in tests from the logs above - seems like Dummy1 did not finish running yet at that point.

**Comment by carlosms** [comment]
That failure should be fixed when we merge #164, I changed it in https://github.com/carlosms/lookout/commit/79c92254803b13aa1c13123bce381ca42d65f27d

**Comment by bzz** [comment]
awesome! Rebased

**Comment by bzz** [comment]
History re-written, waiting CI to pass

Having 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x135af74]

goroutine 32 [running]:
github.com/src-d/lookout/util/cmdtest.failExit()
    ~/go/src/github.com/src-d/lookout/util/cmdtest/cmds.go:161 +0x24
github.com/src-d/lookout/util/cmdtest.(*IntegrationSuite).StartServe.func1(0xc4200de580, 0xc4200a2640, 0xc420124070)
    ~/go/src/github.com/src-d/lookout/util/cmdtest/cmds.go:114 +0x1e7
created by github.com/src-d/lookout/util/cmdtest.(*IntegrationSuite).StartServe
    ~go/src/github.com/src-d/lookout/util/cmdtest/cmds.go:107 +0x49e
FAIL    github.com/src-d/lookout/cmd/server-test    71.202s
make: *** [test-json] Error 1
```
was very confusing, in case when `cmdtest.GrepTrue` could not find a match.

**Pull request merged**
