### PR TITLE
Clarify comments for ReviewEvent.{source,merge}

### PR DESCRIPTION
**Pull request by vmarkovtsev**
After the discussion in the kitchen 26.07

### CODE REVIEW

**Comment by bzz** [comment]
@vmarkovtsev As SDK is in the same codebase with the server, and this change does not include re-generated Protobuf code that is vendored - thus it [fails the CI](https://travis-ci.org/src-d/lookout/jobs/408480677).

You would need to run `make protogen` and include the changes in separate commit to pass the CI

**Comment by vmarkovtsev** [comment]
@bzz I have no idea why editing the comments breaks the build.

```
$ make no-changes-in-commit
diff --git a/pb/event.pb.go b/pb/event.pb.go
index 32e8619..c60e19d 100644
--- a/pb/event.pb.go
+++ b/pb/event.pb.go
@@ -68,7 +68,7 @@ type ReferencePointer struct {
 	InternalRepositoryURL string `protobuf:"bytes,1,opt,name=internal_repository_url,json=internalRepositoryUrl,proto3" json:"internal_repository_url,omitempty"`
 	// ReferenceName is the name of the reference pointing.
 	ReferenceName gopkg_in_src_d_go_git_v4_plumbing.ReferenceName `protobuf:"bytes,2,opt,name=ReferenceName,proto3,casttype=gopkg.in/src-d/go-git.v4/plumbing.ReferenceName" json:"ReferenceName,omitempty"`
-	// Hash is the hash of the reference pointing.
+	// hash is the hash of the reference pointing.
 	Hash string `protobuf:"bytes,3,opt,name=Hash,proto3" json:"Hash,omitempty"`
 }
 
@@ -111,10 +111,9 @@ type ReviewEvent struct {
 	UpdatedAt time.Time `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,stdtime" json:"updated_at"`
 	// IsMergeable, if the pull request is mergeable.
 	IsMergeable bool `protobuf:"varint,5,opt,name=is_mergeable,json=isMergeable,proto3" json:"is_mergeable,omitempty"`
-	// Source reference to the original branch and repository were the changes
-	// came from.
+	// Source reference to the original branch and repository where the changes came from.
 	Source ReferencePointer `protobuf:"bytes,8,opt,name=source" json:"source"`
-	// Merge test branch where the PullRequest was merged.
+	// Merge branch in the destination repository where the Pull Request is stored.
 	Merge ReferencePointer `protobuf:"bytes,9,opt,name=merge" json:"merge"`
 	// Configuration contains any configuration related to specific analyzer
 	Configuration  google_protobuf2.Struct `protobuf:"bytes,10,opt,name=configuration" json:"configuration"`
 M pb/event.pb.go
generated assets are out of sync
make: *** [no-changes-in-commit] Error 2
The command "make no-changes-in-commit" exited with 2.
```

I don't see `no-changes-in-commit` in the top-level Makefile so I am clueless.

**Comment by smacker** [comment]
@vmarkovtsev `no-changes-in-commit` is defined in [.travis.yml](https://github.com/src-d/lookout/blob/master/.travis.yml#L48). For us, it's the easiest way to make sure proto files and code are in sync. (different comments in code & proto means they arent).

To pass CI you need to run `make protogen` and commit changes of go files. If you don't have necessary dependencies for that, please let me know, I'll run it on top of your changes and push to this branch.

**Comment by smacker** [comment]
One more thing. Do you guys need this field? I'm not sure other providers would have it, so maybe we could just remove it?

**Comment by vmarkovtsev** [comment]
We are not using them.

**Comment by bzz** [comment]
+1 for clarification in comments that @smacker proposed. 

But if both GH and Bitbuket do provide it, I would keep it at least for now. 

May be worth to file a separate issue - remove un-used fields?

**Comment by smacker** [comment]
@bzz in gitlab & bitbucket there is a field with the same name but different purpose.

All descriptions:
- Merge test branch where the PullRequest was merged.
- Merge branch in the destination repository where the Pull Request is stored.
- Merge branch that contains a base branch + merge commit

are valid only for github.

For other providers it will be something like:
- Point to merge commit after the PullRequest is successfully merged

That's why I'm raising this question here.

**Comment by bzz** [comment]
Thank you for explanations about different providers!

Yes, that does not make sense to have provider-specific behaviour documented in our API, esp in case it is not beeing used.

Removing it 🙏 using separate PR and 🙏 mentioning it in Release note's change makes much more sense to me as well now.

**Comment by bzz** [comment]
Rebased and code re-generated.

Will merge if there is no further discussion

**Comment by smacker** [comment]
huh? `ReferencePointer` isn't a repository. At least in terms of git.

**Comment by smacker** [comment]
Comment should start with the name if attribute.

I see for source description is
```
// Source reference to the original branch and repository where the changes came from.
```

Maybe we can do similar?
```
// Merge reference to the branch and repository where the merged Pull Request is stored.
```

wdyt?

**Comment by bzz** [comment]
Sounds good, addressed in 1e6e064

**Pull request merged**
