### PR TITLE
stg: installation_sync_interval -> 5m

### PR DESCRIPTION
**Pull request by bzz**
Change github provider installation_sync_interval to 5 min

### CODE REVIEW

**Comment by bzz** [comment]
Unit tests failed in strange and seemingly un-related way

```
    --- FAIL: TestServerCancel/get-files-size-7-cancel-at-0 (0.00s)
        require.go:248: 
            	Error Trace:	data_test.go:205
            	Error:      	An error is expected but got nil.
            	Test:       	TestServerCancel/get-files-size-7-cancel-at-0
    --- PASS: TestServerCancel/get-changes-size-7-cancel-at-1 (0.00s)
```

re-started the CI

**Comment by carlosms** [comment]
Why don't we go ahead and change also the default to a few minutes? 5m looks ok to me. 1h seems excessive for any use-case.

**Comment by bzz** [comment]
that sounds good, default changed in 03a12ac

**Comment by bzz** [comment]
CI is green after 2 restarts :/

**Pull request merged**
