### PR TITLE
Allow to disable analyzers with .lookout.yml

### LINKED ISSUE #191: Could not disable lookout for a repository
After adding a `.lookout.yml` https://github.com/bblfsh/uast-viewer/blob/master/.lookout.yml there are still comments from `lookout-bot` https://github.com/bblfsh/uast-viewer/pull/60

Changing `Dummy` to `dummy` also results in unexpected
```
{"app":"lookout","event-id":"4cac6ace4897c8c6ba65b6c1fa7e1da8c3f37d37","event-type":2,"head":"refs/pull/59/head","level":"warning","msg":"analyzer 'dummy' required by local config isn't enabled on server","provider":"github","repository":"git://github.com/bblfsh/uast-viewer.git","source":"server/server.go:234","time":"2018-08-24T17:46:20.333795614Z"}
```

### PR DESCRIPTION
**Pull request by carlosms**
Fix #191.

### CODE REVIEW

**Comment by bzz** [comment]
👍 do you think it could be worth also having an integration test for this? 

BTW `lookout — There was an error during the analysis` did you have a chance to look into the reason?

**Comment by carlosms** [comment]
> 👍 do you think it could be worth also having an integration test for this? 

Definitely this should have integration tests.
I didn't add any because I think this will be done better when we have the test repository #134. We already have [a comment](https://github.com/src-d/lookout/issues/134#issuecomment-412847756) for PRs with `.lookout.yml` and disabled analyzers.

> BTW `lookout — There was an error during the analysis` did you have a chance to look into the reason?

I see this in the logs:
`posting analysis failed: file not found: cmd/server-test/dummy_analyzer_test.go`

It seems to be failing because this merge is not a _fast-forward_, there are commits in master that are not in this branch. And `dummy_analyzer_test.go` is a file changed in one of those commits in master.
```
lookout fix-disable-analyzers= $ git diff --stat HEAD^
 server/server.go | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

lookout fix-disable-analyzers= $ git diff --stat origin/master 
 cmd/server-test/dummy_analyzer_test.go |  6 ++----
 cmd/server-test/multi_analyzer_test.go | 15 +++++----------
 dummy/dummy.go                         | 17 +++++++----------
 server/server.go                       |  3 ++-
 4 files changed, 16 insertions(+), 25 deletions(-)
```

I'm not sure if the problem is in the lookout server or the dummy analyzer.
We can create a new issue, or add this to #134. What do you think is better?

**Comment by bzz** [comment]
Makes sense for having a separate issue, otherwise that one will grow infinity. 
It will depend on such repository beeing created, but will include updating it to have a reproducible case WDY?

`"error":"posting analysis failed: file not found: cmd/server-test/dummy_analyzer_test.go","event-id":"0cff484868305255034c987578415cfb1db20869` but if I grep for this envent-id occurs 3077 times 😕 - is that expected

**Comment by carlosms** [comment]
New issue: https://github.com/src-d/lookout/issues/197

As for 
> but if I grep for this envent-id occurs 3077 times 😕 - is that expected?

Yes, we log `event processing failed, skipping...` every few seconds.

**Pull request merged**
