### PR TITLE
Review command

### PR DESCRIPTION
**Pull request by smacker**
Review command part of #8 

- rename `analyze` command to `review`
- change arguments according to the issue description
- temporary workaround to avoid ugly logging

### CODE REVIEW

**Comment by smacker** [comment]
@carlosms the problem is described in commit. Copy-paste from there:
```
All log messages are prefixed with "ERROR: logging before flag.Parse"
now.

Read more here: kubernetes/kubernetes#17162

Later we will need to implement grpclog.LoggerV2 interface using
src-d/go-log.
```

Example of old output:
```
ERROR: logging before flag.Parse: I0716 12:20:16.604868   93013 resolver_conn_wrapper.go:116] ccResolverWrapper: sending new addresses to cc: [{localhost:10301 0  <nil>}]
ERROR: logging before flag.Parse: I0716 12:20:16.604889   93013 clientconn.go:823] ClientConn switching balancer to "pick_first"
ERROR: logging before flag.Parse: I0716 12:20:16.604996   93013 pickfirst.go:71] pickfirstBalancer: HandleSubConnStateChange: 0xc420056090, CONNECTING
ERROR: logging before flag.Parse: I0716 12:20:16.607182   93013 pickfirst.go:71] pickfirstBalancer: HandleSubConnStateChange: 0xc420056090, READY
```

Example of new output:
```
2018/07/16 12:40:44 ccResolverWrapper: sending new addresses to cc: [{localhost:10302 0  <nil>}]
2018/07/16 12:40:44 pickfirstBalancer: HandleSubConnStateChange: 0xc42006a070, READY
2018/07/16 12:40:44 ClientConn switching balancer to "pick_first"
2018/07/16 12:40:44 pickfirstBalancer: HandleSubConnStateChange: 0xc4201aba20, CONNECTING
2018/07/16 12:40:44 pickfirstBalancer: HandleSubConnStateChange: 0xc4201aba20, READY
```

Here is an issue for that https://github.com/src-d/lookout/issues/11

**Comment by carlosms** [comment]
thank you, somehow I missed the commit message

**Comment by bzz** [comment]
Shall we rename `analyze.go` -> `review.go` as well?

**Comment by smacker** [comment]
👍 renamed

**Comment by bzz** [comment]
As discussed, lets include 1 and 3 from https://github.com/src-d/lookout/issues/8#issuecomment-405621351 in here

**Comment by smacker** [comment]
@bzz updated, please another pass

**Comment by bzz** [comment]
Looks great! 👍 

One thing - it would be really nice to include a `test plan` section in the PR description.
It would be really great, if a simplest way to test correctness of the changes is told by the author. 

I.e for this one it could be simple as:
 - `make protogen`
 - `go build ./cmd/lookout`

Rationale is 
 - in many cases, it's not as simple as `running the tests`
 - this allows to remove as much guesswork for a person reviewing the changes as possible

Best software engineers in the world [do this](https://github.com/Khan/khan-linter/commit/b69aaac3717c6b9c6964552d80c6e7f443b785ae), so I belive we could benefit from this as well.

**Comment by bzz** [comment]
Looks great!

One thing is - it would be really nice to include a `test plan` in the PR description.

I.e this one introduces

**Comment by smacker** [comment]
sorry I don't get your message about test plan.

You don't need `make protogen` we keep generated code inside the git.
`make tests` makes sure the code is compilable so you don't need `go build` too.

You can do local integration test but I don't see any reason to put it here. All arguments changes are described in the issue.

**Comment by bzz** [comment]
Let me try to explain: as an author of changes, one of your goals is to merge it fast. In order to do so, one of the most efficient strategies that I know is to make reviewers job as simple as possible. Easiest way to do so, is to remove guesswork on how these particular changes are to be tested.

Sorry if that was not clear! 

In example at hand:

> You don't need make protogen we keep generated code inside the git.

Hm, a bit confused then, what is your suggestion to reviewer on how to test if https://github.com/src-d/lookout/pull/9/files#diff-b67911656ef5d18c4ae36cb6741b7965R17 breaks anything or not?

> make tests makes sure the code is compilable so you don't need go build too

indeed, and this sounds great - it would be nice to have `go test` as part of specified test plan for these changes indeed!

**Comment by smacker** [comment]
Ah. I see what you mean now. Thank you for the explanation. As an overall solution, I would suggest to create issues for documentation and proper CI (not only unit tests as right now but code gen and integration tests). Until that issues are resolved we can pause development. It will be much more productive than copy-pasting the same instruction in PR description and running all that commands locally by every reviewer in different environments.

The reasoning is below:

> as an author of changes, one of your goals is to merge it fast

let me disagree with it. It's the team's responsibility to merge fast or slow depends on the priorities, particular changes, impact to the code base, product needs, and many other factors.

> Easiest way to do so, is to remove guesswork on how these particular changes are to be tested

I'm not sure what guesswork you are talking about. All changes are described in the issue. Adding `go run` instruction to each PR if we are developing go application looks like unnecessary noise for me. Similar to the instruction how to install go, bblfsh or how to buy a laptop. Or do you mean we need to add CONTRIBUTING.md with a description of dependencies and how to do integration testing? (and most probably script + CI)

> Hm, a bit confused then, what is your suggestion to reviewer on how to test if https://github.com/src-d/lookout/pull/9/files#diff-b67911656ef5d18c4ae36cb6741b7965R17 breaks anything or not?

I would expect to have a CI step for it. This command depends on protoc. If your protoc is too old/new it might fail. Before the recent change, it was failing even with correct protoc because gogo dependency wasn't vendored too. Currently, we don't have such CI step or any documentation for contributing with deps requirements.

**Comment by bzz** [comment]
> I'm not sure what guesswork you are talking about. 

I was talking about potential guesswork, required from the reviewer to access the impact of changes and the best way to verify that those do not break anything.

> I would expect to have a CI step for it.

👍 that is a great idea

My point was: let's try adding a `test plan` section to the future PR description.

**Comment by smacker** [comment]
There is a small code cov reduction (-0.13%) due to correct handling of lack of HEAD file in dummy analyzer.
Though I don't see any simple fixture with delete/rename of a file. IMO it's not critical to cover dummy analyzer completely.

I'm merging this PR if there is no further discussion.

**Comment by bzz** [comment]
>> I would expect to have a CI step for it.
>
> 👍 that is a great idea

https://github.com/src-d/lookout/issues/24

**Pull request merged**
