### PR TITLE
Lookout verbose option

### PR DESCRIPTION
**Pull request by smacker**
Second (zero) part of #29

### CODE REVIEW

**Comment by bzz** [comment]
Do you think there is a value to have some logs printed for opening/closing a connection  in non-verbose mode?

Right now experience using `time ./lookout review ipv4://localhost:10302` is a bit confusing - after running it, one needs to wait ~3-4sec when nothing happens until `BEGIN RESULT` shows up.

Suggestion:
1. Success 
```
Connected to analyzer at XXX
Sending NotifyReview request
``` 
if something like this is printed, a user would have more patience. 

2. Failure
Right now, if `time ./lookout review ipv4://localhost:666` just has no feedback to user at all.
Suggestion:
```
Failed to connect to analyzer at XXX
Retrying (1 out of Y)
...
Failed to connect to analyzer at XXX
Retrying (2 out of Y)
``` 

Having both of those would allow to wave the mistakes related to networking for a user and thus help building a trust in SDK (he does not need to check with `nc` manually if server is reachable, etc)

Also, do you think there is a value of applying same `-v` for dummy analyzer as well? 
May be does not need to be that detailed, but may be nice to have

**Comment by smacker** [comment]
@bzz 
> Failure to connect to analyzer without -v it's very hard to identify: does it taking to long? does it fail to connect?
this is why commits are in opposite order to issue bullets. 

With the prev commit it will fail fast with correct error.

**Comment by bzz** [comment]
> would be nice 👍 let's update issue/create new one with description of proper success logging across binaries and implement it.

Improving in separate issue sounds good - would you please create one so the feedback is not getting lost?

**Comment by smacker** [comment]
rebased on master. Merge after CI is green.

**Pull request merged**
